#import "../fragments/galleryFields.gql"
#import "../fragments/pageInfo.gql"

# Fetch all galleries (no user filtering)
query GetGalleries {
  galleries {
    ...GalleryFields
  }
}

# Fetch a single gallery by ID, with its photos
query GetGallery($id: ID!) {
  gallery(id: $id) {
    ...GalleryFields
    photos {
      ...PhotoFields
    }
  }
}

# Paginated Galleries
query GetGalleriesPaginated($after: String, $first: Int = 10) {
  galleriesPaginated(after: $after, first: $first) {
    edges {
      cursor
      node {
        ...GalleryFields
      }
    }
    pageInfo {
      ...PageInfoFields
    }
  }
}
