#import "../fragments/photoFields.gql"
#import "../fragments/pageInfo.gql"

# Fetch ALL photos (unassigned + assigned)
query GetPhotos {
  photos {
    ...PhotoFields
  }
}

# Fetch only photos assigned to a gallery
query GetGalleryPhotos($galleryId: ID!) {
  galleryPhotos(galleryId: $galleryId) {
    ...PhotoFields
  }
}

# Paginated ALL photos
query GetPhotosPaginated($after: String, $first: Int = 10) {
  photosPaginated(after: $after, first: $first) {
    edges {
      cursor
      node {
        ...PhotoFields
      }
    }
    pageInfo {
      ...PageInfoFields
    }
  }
}
